Repository cpatrickalves/kaggle-houses-prices-prediction, pull requests merged in 2020-06, with the labels that each got.

#11 Metrics info added in guide-questions
  README.md
  guide_questions/readme.md
Labels: documentation

#13 Feature/basic api
  Pipfile
  Pipfile.lock
  README.md
  requirements.txt
  src/api/README.md
  src/api/api.py
  src/api/test_api.py
  src/models/predict.py
Labels: enhancement

#17 Demo UI using Streamlit
  Pipfile
  Pipfile.lock
  requirements.txt
  src/poc/README.md
  src/poc/app.py
Labels: enhancement

#18 Update streamlit folder and readme
  src/demo/README.md
  src/poc/README.md
  src/poc/app.py
Labels: invalid

#19 Create new train and test datasets
  README.md
  data/from_kaggle/test.csv
  data/from_kaggle/train.csv
  data/raw/test.csv
  data/raw/train.csv
  settings.py
  src/data/split_data.py
Labels: enhancement
